# Generated by Django 4.0.3 on 2022-03-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depastment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depastment_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateof_joining', models.DateTimeField(auto_now_add=True)),
                ('employee_name', models.CharField(max_length=255)),
                ('depastment', models.CharField(max_length=255)),
            ],
        ),
    ]
